services:
  nerfstudio:
    build:
      context: .
      dockerfile: Dockerfile.nerfstudio
    image: nerfstudio:5090-cuda12.8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_CACHE_HOME=/workspace/cache
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../datasets:/workspace/datasets
      - ../output:/workspace/output
      - ../thirdparty:/workspace/thirdparty
      - ../cache:/workspace/cache
      - .:/workspace/nerfstudio_context
    ports:
      - "7007:7007"
    shm_size: 32gb
    stdin_open: true # -i
    tty: true        # -t
    working_dir: /workspace/data
    command: bash
