services:
  nksr:
    build:
      context: .
      dockerfile: Dockerfile.nksr
    image: vision_lab/nksr:cuda12.8
    container_name: nksr_container
    runtime: nvidia
    network_mode: host
    command: ["tail", "-f", "/dev/null"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics,display
      - DISPLAY=${DISPLAY}
      - QT_XCB_GL_INTEGRATION=xcb_glx
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - XDG_CACHE_HOME=/workspace/cache
    volumes:
      - ../datasets:/workspace/datasets
      - ../output:/workspace/output
      - ../thirdparty:/workspace/thirdparty
      - ../cache:/workspace/cache
      - .:/workspace/nksr_context
